/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as IosRouteImport } from './routes/ios'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as MemeIdRouteImport } from './routes/meme.$id'
import { Route as ApiMemeIdRouteImport } from './routes/api/meme.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const IosRoute = IosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const MemeIdRoute = MemeIdRouteImport.update({
  id: '/meme/$id',
  path: '/meme/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemeIdRoute = ApiMemeIdRouteImport.update({
  id: '/api/meme/$id',
  path: '/api/meme/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/generate': typeof GenerateRoute
  '/ios': typeof IosRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/img': typeof ApiImgRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/meme/$id': typeof MemeIdRoute
  '/api/meme/$id': typeof ApiMemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/generate': typeof GenerateRoute
  '/ios': typeof IosRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/img': typeof ApiImgRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/meme/$id': typeof MemeIdRoute
  '/api/meme/$id': typeof ApiMemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/generate': typeof GenerateRoute
  '/ios': typeof IosRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/img': typeof ApiImgRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/meme/$id': typeof MemeIdRoute
  '/api/meme/$id': typeof ApiMemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/generate'
    | '/ios'
    | '/api/feed'
    | '/api/img'
    | '/api/templates'
    | '/meme/$id'
    | '/api/meme/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/generate'
    | '/ios'
    | '/api/feed'
    | '/api/img'
    | '/api/templates'
    | '/meme/$id'
    | '/api/meme/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/generate'
    | '/ios'
    | '/api/feed'
    | '/api/img'
    | '/api/templates'
    | '/meme/$id'
    | '/api/meme/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GenerateRoute: typeof GenerateRoute
  IosRoute: typeof IosRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiImgRoute: typeof ApiImgRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  MemeIdRoute: typeof MemeIdRoute
  ApiMemeIdRoute: typeof ApiMemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios': {
      id: '/ios'
      path: '/ios'
      fullPath: '/ios'
      preLoaderRoute: typeof IosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meme/$id': {
      id: '/meme/$id'
      path: '/meme/$id'
      fullPath: '/meme/$id'
      preLoaderRoute: typeof MemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meme/$id': {
      id: '/api/meme/$id'
      path: '/api/meme/$id'
      fullPath: '/api/meme/$id'
      preLoaderRoute: typeof ApiMemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GenerateRoute: GenerateRoute,
  IosRoute: IosRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiImgRoute: ApiImgRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  MemeIdRoute: MemeIdRoute,
  ApiMemeIdRoute: ApiMemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
